A scrpt that prints out a sentence

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,13 +1,11 @@
 #!/usr/bin/python3
+if [ -z "$PYFILE" ]; then
+  echo 'Error: PYFILE environment variable is not set'
+  exit 1
+fi
+if [ ! -f "$PYFILE" ]; then
+  echo "Error: Python file '$PYFILE' not found"
+  exit 1
+fi
+python3 "$PYFILE"
 
-import os
-
-if not os.environ.get("PYFILE"):
-    print('error, environment variable is not set')
-    exit(11)
-
-pyfile = os.environ["PYFILE"]
-
-if not os.path.isfile(pyfile):
-    print('error, python file not found')
-    exit(1)
